name: itmo_dart_asg
description: Abstract Semantic Graph builder for Dart programs
version: 1.0.0
repository: https://github.com/MaKsY2/itmo-dart-asg

environment:
  sdk: ^3.5.4

dependencies:
  analyzer: ^7.7.1
  path: ^1.9.1
  collection: ^1.19.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0